name: inclass17
description: FCM Demo App
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
